import { Product, StoreLocation, Service, CompanyInfo } from './types';

export const CATEGORIES = [
  { name: 'All', icon: '🛍️' },
  { name: 'Groceries', icon: '🥦' },
  { name: 'Clothing', icon: '👕' },
  { name: 'Electronics', icon: '📱' },
  { name: 'Furniture', icon: '🪑' },
  { name: 'Automobiles', icon: '🚗' },
  { name: 'Hardware', icon: '🔨' },
  { name: 'Digital Products', icon: '🖥️' },
  { name: 'Services', icon: '🔧' },
  { name: 'Digital Services', icon: '💻' },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Fresh Organic Apples (1kg)',
    price: 150,
    category: 'Groceries',
    condition: 'New',
    image: 'https://picsum.photos/400/400?random=1',
    description: 'Fresh farm-picked organic apples.',
    rating: 4.8,
    inStock: true,
  },
  {
    id: '2',
    name: 'Vintage Leather Sofa',
    price: 12000,
    category: 'Furniture',
    condition: 'Used',
    image: 'https://picsum.photos/400/400?random=2',
    description: 'Classic 3-seater leather sofa, excellent condition.',
    rating: 4.5,
    inStock: true,
  },
  {
    id: '3',
    name: 'iPhone 15 Pro Max',
    price: 159900,
    category: 'Electronics',
    condition: 'New',
    image: 'https://picsum.photos/400/400?random=3',
    description: 'Brand new, sealed box with warranty.',
    rating: 5.0,
    inStock: true,
  },
  {
    id: '4',
    name: 'Used Honda City (2018)',
    price: 650000,
    category: 'Automobiles',
    condition: 'Used',
    image: 'https://picsum.photos/400/400?random=4',
    description: 'Well maintained, single owner, 40k km driven.',
    rating: 4.2,
    inStock: true,
  },
  {
    id: '5',
    name: 'Men\'s Cotton Shirt',
    price: 899,
    category: 'Clothing',
    condition: 'New',
    image: 'https://picsum.photos/400/400?random=5',
    description: 'Premium cotton formal shirt.',
    rating: 4.6,
    inStock: true,
  },
  {
    id: '6',
    name: 'Aluminium Sliding Window',
    price: 4500,
    category: 'Hardware',
    condition: 'New',
    image: 'https://picsum.photos/400/400?random=6',
    description: 'Custom size aluminium glass window.',
    rating: 4.7,
    inStock: true,
  },
  {
    id: '7',
    name: 'Second-hand Study Table',
    price: 1500,
    category: 'Furniture',
    condition: 'Used',
    image: 'https://picsum.photos/400/400?random=7',
    description: 'Wooden study table, minor scratches.',
    rating: 3.8,
    inStock: true,
  },
  {
    id: '8',
    name: 'Basmati Rice (5kg)',
    price: 600,
    category: 'Groceries',
    condition: 'New',
    image: 'https://picsum.photos/400/400?random=8',
    description: 'Premium long grain basmati rice.',
    rating: 4.9,
    inStock: true,
  },
  {
    id: '9',
    name: 'Organic Raw Honey (500g)',
    price: 350,
    category: 'Groceries',
    condition: 'New',
    image: 'https://picsum.photos/400/400?random=9',
    description: 'Pure, unprocessed organic honey from Himalayas.',
    rating: 4.9,
    inStock: true,
  },
  {
    id: '10',
    name: 'Dell Latitude Laptop (i5, 8GB)',
    price: 18500,
    category: 'Digital Products',
    condition: 'Used',
    image: 'https://picsum.photos/400/400?random=10',
    description: 'Refurbished corporate laptop, excellent battery life.',
    rating: 4.3,
    inStock: true,
  },
  {
    id: '11',
    name: 'Teak Wood Dining Table (6 Seater)',
    price: 25000,
    category: 'Furniture',
    condition: 'New',
    image: 'https://picsum.photos/400/400?random=11',
    description: 'Solid teak wood dining table with glass top.',
    rating: 4.7,
    inStock: true,
  },
  {
    id: '12',
    name: 'Royal Enfield Classic 350 (2019)',
    price: 110000,
    category: 'Automobiles',
    condition: 'Used',
    image: 'https://picsum.photos/400/400?random=12',
    description: 'Mint condition, army green color, 15k km driven.',
    rating: 4.6,
    inStock: true,
  },
  {
    id: '13',
    name: 'Bosch Power Drill Kit',
    price: 4200,
    category: 'Hardware',
    condition: 'New',
    image: 'https://picsum.photos/400/400?random=13',
    description: '500W impact drill with 100pcs accessory set.',
    rating: 4.8,
    inStock: true,
  },
  {
    id: '14',
    name: 'Women\'s Cotton Kurta Set',
    price: 1299,
    category: 'Clothing',
    condition: 'New',
    image: 'https://picsum.photos/400/400?random=14',
    description: 'Elegant printed cotton kurta with palazzo.',
    rating: 4.5,
    inStock: true,
  },
   {
    id: '15',
    name: 'Sony WH-1000XM5 Headphones',
    price: 26990,
    category: 'Digital Products',
    condition: 'New',
    image: 'https://picsum.photos/400/400?random=15',
    description: 'Industry leading noise canceling headphones.',
    rating: 5.0,
    inStock: true,
  },
  {
    id: '16',
    name: 'Used Office Chair (Ergonomic)',
    price: 3500,
    category: 'Furniture',
    condition: 'Used',
    image: 'https://picsum.photos/400/400?random=16',
    description: 'Adjustable height and lumbar support, good condition.',
    rating: 4.0,
    inStock: true,
  },
  {
    id: '17',
    name: 'Aashirvaad Whole Wheat Atta (5kg)',
    price: 240,
    category: 'Groceries',
    condition: 'New',
    image: 'https://picsum.photos/400/400?random=17',
    description: '100% whole wheat flour, high in fiber.',
    rating: 4.8,
    inStock: true,
  },
  {
    id: '18',
    name: 'Fortune Sunflower Oil (1L)',
    price: 165,
    category: 'Groceries',
    condition: 'New',
    image: 'https://picsum.photos/400/400?random=18',
    description: 'Light and healthy sunflower oil for daily cooking.',
    rating: 4.6,
    inStock: true,
  },
  {
    id: '19',
    name: 'Coca-Cola Can (Pack of 6)',
    price: 240,
    category: 'Groceries',
    condition: 'New',
    image: 'https://picsum.photos/400/400?random=19',
    description: 'Refreshing soft drink, pack of 6 cans.',
    rating: 4.7,
    inStock: true,
  },
  {
    id: '20',
    name: 'Fresh Tomatoes (1kg)',
    price: 40,
    category: 'Groceries',
    condition: 'New',
    image: 'https://picsum.photos/400/400?random=20',
    description: 'Farm fresh red tomatoes.',
    rating: 4.5,
    inStock: true,
  },
  {
    id: '21',
    name: 'Samsung Galaxy S24 Ultra',
    price: 129999,
    category: 'Digital Products',
    condition: 'New',
    image: 'https://picsum.photos/400/400?random=21',
    description: 'AI-powered smartphone with titanium frame.',
    rating: 4.9,
    inStock: true,
  },
  {
    id: '22',
    name: 'Used iPhone 13 (128GB)',
    price: 35000,
    category: 'Digital Products',
    condition: 'Used',
    image: 'https://picsum.photos/400/400?random=22',
    description: 'Midnight color, 85% battery health, minor scratches.',
    rating: 4.1,
    inStock: true,
  },
  {
    id: '23',
    name: 'King Size Bed with Storage',
    price: 32000,
    category: 'Furniture',
    condition: 'New',
    image: 'https://picsum.photos/400/400?random=23',
    description: 'Engineered wood king size bed with hydraulic storage.',
    rating: 4.6,
    inStock: true,
  },
  {
    id: '24',
    name: 'Used Wardrobe (3 Door)',
    price: 8000,
    category: 'Furniture',
    condition: 'Used',
    image: 'https://picsum.photos/400/400?random=24',
    description: 'Wooden wardrobe, good condition, ample storage.',
    rating: 3.9,
    inStock: true,
  },
  {
    id: '25',
    name: 'Nike Air Max Sneakers',
    price: 8500,
    category: 'Clothing',
    condition: 'New',
    image: 'https://picsum.photos/400/400?random=25',
    description: 'Stylish and comfortable running shoes.',
    rating: 4.8,
    inStock: true,
  },
  {
    id: '26',
    name: 'Banarasi Silk Saree',
    price: 4500,
    category: 'Clothing',
    condition: 'New',
    image: 'https://picsum.photos/400/400?random=26',
    description: 'Traditional red silk saree with gold zari work.',
    rating: 4.7,
    inStock: true,
  },
  {
    id: '27',
    name: 'Car Vacuum Cleaner',
    price: 1200,
    category: 'Automobiles',
    condition: 'New',
    image: 'https://picsum.photos/400/400?random=27',
    description: 'High power portable vacuum cleaner for cars.',
    rating: 4.3,
    inStock: true,
  },
  {
    id: '28',
    name: 'Studds Ninja Helmet',
    price: 1500,
    category: 'Automobiles',
    condition: 'New',
    image: 'https://picsum.photos/400/400?random=28',
    description: 'Full face helmet with clear visor, ISI certified.',
    rating: 4.5,
    inStock: true,
  },
  {
    id: '29',
    name: 'Taparia Tool Kit (101 Pcs)',
    price: 2800,
    category: 'Hardware',
    condition: 'New',
    image: 'https://picsum.photos/400/400?random=29',
    description: 'Comprehensive home tool set with box.',
    rating: 4.6,
    inStock: true,
  },
  {
    id: '30',
    name: 'Bathroom Mixer Tap',
    price: 2200,
    category: 'Hardware',
    condition: 'New',
    image: 'https://picsum.photos/400/400?random=30',
    description: 'Brass chrome finish wall mixer for bathroom.',
    rating: 4.4,
    inStock: true,
  },
  {
    id: '31',
    name: 'Used Bluetooth Speaker (JBL)',
    price: 3000,
    category: 'Electronics',
    condition: 'Used',
    image: 'https://picsum.photos/400/400?random=31',
    description: 'JBL Flip 4, good sound quality, charger included.',
    rating: 4.2,
    inStock: true,
  },
  {
    id: '32',
    name: 'Bean Bag with Beans (XL)',
    price: 1800,
    category: 'Furniture',
    condition: 'New',
    image: 'https://picsum.photos/400/400?random=32',
    description: 'Comfortable artificial leather bean bag.',
    rating: 4.5,
    inStock: true,
  },
  // --- NEW DIGITAL PRODUCTS ---
  {
    id: 'dp1',
    name: 'HP All-in-One Desktop PC',
    price: 55000,
    category: 'Digital Products',
    condition: 'New',
    image: 'https://picsum.photos/400/400?random=70',
    description: 'i5 12th Gen, 8GB RAM, 512GB SSD, 24" FHD Display.',
    rating: 4.6,
    inStock: true,
  },
  {
    id: 'dp2',
    name: 'Canon Pixma Color Printer',
    price: 14500,
    category: 'Digital Products',
    condition: 'New',
    image: 'https://picsum.photos/400/400?random=71',
    description: 'All-in-One Wireless Ink Tank Colour Printer.',
    rating: 4.4,
    inStock: true,
  },
  {
    id: 'dp3',
    name: 'CP Plus CCTV Camera Set (4ch)',
    price: 12000,
    category: 'Digital Products',
    condition: 'New',
    image: 'https://picsum.photos/400/400?random=72',
    description: '4 Channel DVR with 4 Bullet Cameras, Night Vision.',
    rating: 4.7,
    inStock: true,
  },
  {
    id: 'dp4',
    name: 'TP-Link Archer AX1500 WiFi 6 Router',
    price: 3200,
    category: 'Digital Products',
    condition: 'New',
    image: 'https://picsum.photos/400/400?random=73',
    description: 'Next-Gen Wi-Fi 6, Dual-Band Gigabit Router.',
    rating: 4.8,
    inStock: true,
  },
  {
    id: 'dp5',
    name: 'Samsung 55" Crystal 4K UHD TV',
    price: 45990,
    category: 'Digital Products',
    condition: 'New',
    image: 'https://picsum.photos/400/400?random=74',
    description: 'Smart TV with Slim Fit Camera and Object Tracking Sound.',
    rating: 4.8,
    inStock: true,
  },
  {
    id: 'dp6',
    name: 'Maxhub Interactive Digital Board 65"',
    price: 185000,
    category: 'Digital Products',
    condition: 'New',
    image: 'https://picsum.photos/400/400?random=75',
    description: '4K UHD Interactive Flat Panel for Classrooms & Offices.',
    rating: 5.0,
    inStock: true,
  },
  {
    id: 'dp7',
    name: 'Tuter Plus Learning Device',
    price: 24999,
    category: 'Digital Products',
    condition: 'New',
    image: 'https://picsum.photos/400/400?random=76',
    description: 'Educational Tablet with Pre-loaded Content for K-12.',
    rating: 4.5,
    inStock: true,
  },
  {
    id: 'dp8',
    name: 'Sony Alpha ZV-E10 Camera',
    price: 60000,
    category: 'Digital Products',
    condition: 'New',
    image: 'https://picsum.photos/400/400?random=77',
    description: 'Interchangeable-Lens Vlog Camera with 16-50mm Lens.',
    rating: 4.9,
    inStock: true,
  },
  {
    id: 'dp9',
    name: 'Logitech Wireless Combo MK270',
    price: 1695,
    category: 'Digital Products',
    condition: 'New',
    image: 'https://picsum.photos/400/400?random=78',
    description: 'Wireless Keyboard and Mouse Combo for Windows.',
    rating: 4.3,
    inStock: true,
  }
];

export const MOCK_SERVICES: Service[] = [
  // --- Home Services ---
  {
    id: 's1',
    name: 'Home Plumbing Service',
    category: 'Services',
    priceRange: '₹500 - ₹2000',
    description: 'Expert plumbers for repairs and installation.',
    image: 'https://picsum.photos/400/400?random=20',
    rating: 4.5,
  },
  {
    id: 's2',
    name: 'AC Repair & Service',
    category: 'Services',
    priceRange: '₹800 - ₹1500',
    description: 'Professional AC cleaning and gas filling.',
    image: 'https://picsum.photos/400/400?random=21',
    rating: 4.7,
  },
  {
    id: 's3',
    name: 'Interior Design Consultation',
    category: 'Services',
    priceRange: '₹2000 onwards',
    description: 'Transform your home with expert advice.',
    image: 'https://picsum.photos/400/400?random=22',
    rating: 4.9,
  },
  {
    id: 's4',
    name: 'Deep Home Cleaning',
    category: 'Services',
    priceRange: '₹3000 - ₹8000',
    description: 'Complete sanitization and deep cleaning for 2BHK/3BHK.',
    image: 'https://picsum.photos/400/400?random=23',
    rating: 4.8,
  },
  {
    id: 's5',
    name: 'Electrician on Call',
    category: 'Services',
    priceRange: '₹300 visit charge',
    description: 'Expert electricians for wiring, fans, and light fitting.',
    image: 'https://picsum.photos/400/400?random=24',
    rating: 4.6,
  },
  {
    id: 's6',
    name: 'Car Spa & Detailing',
    category: 'Services',
    priceRange: '₹1200 onwards',
    description: 'Interior and exterior car cleaning at your doorstep.',
    image: 'https://picsum.photos/400/400?random=25',
    rating: 4.7,
  },
  {
    id: 's7',
    name: 'House Painting Service',
    category: 'Services',
    priceRange: '₹12 - ₹30 per sq ft',
    description: 'Interior and exterior painting by professional painters.',
    image: 'https://picsum.photos/400/400?random=33',
    rating: 4.6,
  },
  {
    id: 's8',
    name: 'Pest Control Service',
    category: 'Services',
    priceRange: '₹800 - ₹2500',
    description: 'Cockroach, termite, and bed bug control treatments.',
    image: 'https://picsum.photos/400/400?random=34',
    rating: 4.8,
  },
  {
    id: 's9',
    name: 'Sofa Cleaning',
    category: 'Services',
    priceRange: '₹250 per seat',
    description: 'Deep vacuuming and shampooing for sofas.',
    image: 'https://picsum.photos/400/400?random=35',
    rating: 4.5,
  },
  {
    id: 's10',
    name: 'Salon for Women (At Home)',
    category: 'Services',
    priceRange: '₹500 onwards',
    description: 'Facials, waxing, and threading at your convenience.',
    image: 'https://picsum.photos/400/400?random=36',
    rating: 4.9,
  },
  {
    id: 's11',
    name: 'Men\'s Haircut & Grooming',
    category: 'Services',
    priceRange: '₹200 onwards',
    description: 'Professional barber services at your doorstep.',
    image: 'https://picsum.photos/400/400?random=37',
    rating: 4.7,
  },
  {
    id: 's12',
    name: 'Carpentry Services',
    category: 'Services',
    priceRange: '₹400 visit charge',
    description: 'Furniture repair, assembly, and custom woodwork.',
    image: 'https://picsum.photos/400/400?random=38',
    rating: 4.4,
  },
  {
    id: 's13',
    name: 'RO Water Purifier Service',
    category: 'Services',
    priceRange: '₹350 - ₹600',
    description: 'Filter change, installation, and general service.',
    image: 'https://picsum.photos/400/400?random=39',
    rating: 4.6,
  },
  // --- Digital Services ---
  {
    id: 'd1',
    name: 'Web Application Development',
    category: 'Digital Services',
    priceRange: '₹15,000 onwards',
    description: 'Custom websites, portals, and web apps using latest tech.',
    image: 'https://picsum.photos/400/400?random=60',
    rating: 5.0,
  },
  {
    id: 'd2',
    name: 'Mobile App Development',
    category: 'Digital Services',
    priceRange: '₹25,000 onwards',
    description: 'Android & iOS apps tailored to your business needs.',
    image: 'https://picsum.photos/400/400?random=61',
    rating: 4.9,
  },
  {
    id: 'd3',
    name: 'Graphics & Logo Design',
    category: 'Digital Services',
    priceRange: '₹2,000 onwards',
    description: 'Creative logos, brochures, social media posts, and UI/UX.',
    image: 'https://picsum.photos/400/400?random=62',
    rating: 4.8,
  },
  {
    id: 'd4',
    name: 'Digital Marketing & SEO',
    category: 'Digital Services',
    priceRange: '₹10,000 / month',
    description: 'Boost your online presence with SEO and Social Media marketing.',
    image: 'https://picsum.photos/400/400?random=63',
    rating: 4.7,
  },
  {
    id: 'd5',
    name: 'Branding & Strategy',
    category: 'Digital Services',
    priceRange: '₹50,000 onwards',
    description: 'Complete brand identity creation and strategy consulting.',
    image: 'https://picsum.photos/400/400?random=64',
    rating: 4.9,
  },
  {
    id: 'd6',
    name: 'Video Editing & Ads',
    category: 'Digital Services',
    priceRange: '₹5,000 onwards',
    description: 'Professional video editing for commercials and reels.',
    image: 'https://picsum.photos/400/400?random=65',
    rating: 4.6,
  }
];

export const STORE_LOCATIONS: StoreLocation[] = [
  {
    id: 'loc1',
    name: 'Zarurat Bazaar HQ',
    address: 'Malviya Nagar, New Delhi, 110017',
    phone: '+91 11 2345 6789',
    coordinates: { lat: 28.5355, lng: 77.2167 },
    image: 'https://picsum.photos/400/400?random=50'
  },
  {
    id: 'loc2',
    name: 'Lajpat Nagar Branch',
    address: 'Central Market, Lajpat Nagar II, New Delhi',
    phone: '+91 11 9876 5432',
    coordinates: { lat: 28.5692, lng: 77.2435 },
    image: 'https://picsum.photos/400/400?random=51'
  }
];

export const COMPANY_INFO: CompanyInfo = {
  name: "Zarurat Bazaar",
  parentCompany: "Yaqoobi Empire Pvt. Ltd.",
  headOffice: "Malviya Nagar, New Delhi, 110017",
  tagline: "Your Daily Needs, Fulfilled.",
  email: "contact@zaruratbazaar.com",
  phone: "+91-11-23456789",
  logoUrl: "" // Empty by default, will fallback to text/CSS logo
};